In [120]:
import sklearn.model_selection
import pandas as pd

# Import BBJ's File!
from hw3_janeane import *

blotter = pd.read_csv('blotter.csv')
print(blotter)

      trade_id     date asset   trip action type     price     status
0            1   1/3/20   IVV  ENTER    BUY  LMT  323.0600  SUBMITTED
1            1   1/3/20   IVV  ENTER    BUY  LMT  323.0600     FILLED
2            1   1/3/20   IVV   EXIT   SELL  LMT  326.2906  SUBMITTED
3            1   1/8/20   IVV   EXIT   SELL  LMT  326.2906     FILLED
4            2   1/6/20   IVV  ENTER    BUY  LMT  320.5700  SUBMITTED
...        ...      ...   ...    ...    ...  ...       ...        ...
2606       810  3/22/23   IVV  ENTER    BUY  LMT  398.2100  SUBMITTED
2607       810  3/22/23   IVV  ENTER    BUY  LMT  398.2100     FILLED
2608       810  3/22/23   IVV   EXIT   SELL  LMT  402.1921  SUBMITTED
2609       810  3/23/23   IVV   EXIT   SELL  LMT  402.1921       LIVE
2610       811  3/23/23   IVV  ENTER    BUY  LMT  391.5400       LIVE

[2611 rows x 8 columns]


In [121]:
ledger = ledger(blotter)
print(ledger)

      trade_id asset dt_enter  dt_exit success  n       rtn
3            1   IVV   1/3/20   1/8/20       1  4  0.002488
5            2   IVV   1/6/20                0  3          
7            3   IVV   1/7/20                0  3          
9            4   IVV   1/8/20                0  3          
11           5   IVV   1/9/20                0  3          
...        ...   ...      ...      ...     ... ..       ...
2601       807   IVV  3/17/23  3/21/23       1  3  0.003317
2603       808   IVV  3/20/23                0  3          
2605       809   IVV  3/21/23                              
2609       810   IVV  3/22/23                              
2610       811   IVV  3/23/23                              

[811 rows x 7 columns]
      trade_id asset dt_enter  dt_exit success  n       rtn
3            1   IVV   1/3/20   1/8/20       1  4  0.002488
5            2   IVV   1/6/20                0  3          
7            3   IVV   1/7/20                0  3          
9            4  

In [122]:
# build your set of features here.
# merge them by date to add to this dataframe.
import pandas as pd
data = pd.read_csv('hw4.csv')
features = data[['ECRPUS 1Y Index','SPXSFRCS Index','FDTRFTRL Index']]
print(features)

     ECRPUS 1Y Index  SPXSFRCS Index  FDTRFTRL Index
0               30.0            3318             1.5
1               30.0            3318             1.5
2               30.0            3318             1.5
3               30.0            3318             1.5
4               30.0            3318             1.5
..               ...             ...             ...
803             60.0            4050             4.5
804             60.0            4050             4.5
805             60.0            4050             4.5
806             60.0            4050             4.5
807             60.0            4050             4.5

[808 rows x 3 columns]


In [123]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.preprocessing import StandardScaler

# Make a training set and let's try it out on two upcoming trades.
# Choose a subset of data:
X = features.head(600)
x_test = features[601:]
y = np.asarray(ledger.success.head(600), dtype="|S6")

print(X)
print(x_test)
print(y)

     ECRPUS 1Y Index  SPXSFRCS Index  FDTRFTRL Index
0               30.0            3318            1.50
1               30.0            3318            1.50
2               30.0            3318            1.50
3               30.0            3318            1.50
4               30.0            3318            1.50
..               ...             ...             ...
595             30.0            4868            0.75
596             30.0            4868            0.75
597             30.0            4787            0.75
598             30.0            4743            0.75
599             30.0            4743            0.75

[600 rows x 3 columns]
     ECRPUS 1Y Index  SPXSFRCS Index  FDTRFTRL Index
601             30.0            4743            0.75
602             30.0            4743            0.75
603             30.0            4743            0.75
604             30.0            4743            0.75
605             30.0            4743            0.75
..               ...  

In [124]:
sc = StandardScaler()

sc.fit(X)
X_std = sc.transform(X)
X_std = sc.transform(X)
x_test_std = sc.transform(x_test)

print(X_std)
from sklearn.decomposition import PCA
pca = PCA(n_components = 1)
X_train = pca.fit_transform(X_std)
X_test = pca.transform(x_test_std)
explained_variance = pca.explained_variance_ratio_


[[-0.13210777 -0.92181501  3.40014402]
 [-0.13210777 -0.92181501  3.40014402]
 [-0.13210777 -0.92181501  3.40014402]
 ...
 [-0.13210777  1.21641756  1.51930221]
 [-0.13210777  1.15237247  1.51930221]
 [-0.13210777  1.15237247  1.51930221]]


In [125]:
ppn = Perceptron(eta0=0.1)
ppn.fit(X_train, y)

y_pred = ppn.predict(X_test)
print(y_pred)

[b'0' b'0' b'0' b'0' b'0' b'0' b'0' b'0' b'0' b'0' b'0' b'0' b'0' b'0'
 b'0' b'0' b'0' b'0' b'0' b'0' b'0' b'0' b'0' b'0' b'0' b'0' b'0' b'0'
 b'0' b'0' b'0' b'0' b'0' b'0' b'0' b'0' b'0' b'0' b'0' b'0' b'0' b'0'
 b'0' b'0' b'0' b'0' b'0' b'0' b'0' b'0' b'0' b'0' b'0' b'0' b'0' b'0'
 b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1'
 b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1'
 b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1'
 b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1'
 b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1'
 b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1'
 b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1'
 b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1'
 b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1'
 b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1' b'1'
 b'1' 

In [126]:
print(ledger.iloc[[51, 52]])

     trade_id asset dt_enter  dt_exit success  n       rtn
178        52   IVV  3/18/20  3/25/20       1  6  0.001658
182        53   IVV  3/19/20  3/19/20       1  1   0.00995
